EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      Layout/LineLength:
        Enabled: false
    only:
      - Layout/LineLength
